apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qtest-pulse-dev
  namespace: argocd
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.applications.qtestpulsedev.namespace }}
    server: {{ .Values.clusters.stage }}
  project: {{ .Values.project }}
  source:
    chart: {{ .Values.applications.qtestpulsedev.chart }}
    repoURL: {{ .Values.qtest.chart }}
    targetRevision: "*"
    helm:
      values: |
        service:
          type: ClusterIP
          port: 4080
          targetport: 4080
        ingress:
          enabled: true
          hosts:
            - pulse.container-dev.qtestdev.com
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:242129367204:certificate/7267f31c-d515-401a-b61b-d1780879b763
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
            alb.ingress.kubernetes.io/group.name: qtest-dev
          paths:
            - /*
        qTestPulse:
          qTestPulsePGUrl: postgresql://postgres:RW9dSqzC6!d!7!ED@qtestproduction.ckial7bswutk.us-east-1.rds.amazonaws.com/pulse
          qTestPulsePort: "4080"
          qTestPulseNodeEnv: production
          qTestPulseRootURL: https://pulse.container-dev.qtestdev.com
          qTestPulseQTestURL: https://qtestdev1.container-dev.qtestdev.com
          qTestPulseScenarioURL: https://scenario.container-dev.qtestdev.com
          qTestPulseNodeTLSRejectUnAuthorized: "0"
        autoscaling:
          enabled: false