apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kubernetes-external-secrets
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: "*"
    helm:
      values: |
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
        securityContext:
          fsGroup: 65534
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::242129367204:role/AmazonEKS_Secrets_Manager_Role"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true