apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: argoproj
  name: litmus
  namespace: argocd
spec:
  destination:
    namespace: litmus
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: litmus
    repoURL: 'https://litmuschaos.github.io/litmus-helm/'
    targetRevision: "*"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/validation
      kind: CustomResourceDefinition
