apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: qtest
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: ecr-creds-dev
      name: ".dockerconfigjson"
      property: DOCKER_CONFIG