apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  name: cluster-resources
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: kubernetes/cluster-resources/*.json
      repoURL: https://github.com/byangtri/eks-argo-platform.git
      requeueAfterSeconds: 20
      revision: applicationset
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-resources-{{name}}
      name: cluster-resources-{{name}}
      namespace: argocd
    spec:
      destination:
        server: '{{server}}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: default
      source:
        path: kubernetes/cluster-resources/{{name}}
        repoURL: https://github.com/byangtri/eks-argo-platform.git
        targetRevision: applicationset
      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      # files:
      # - path: kubernetes/cluster-addons/**/config.json
      repoURL: https://github.com/byangtri/eks-argo-platform.git
      revision: applicationset
      directories:
      - path: kubernetes/cluster-addons/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/byangtri/eks-argo-platform.git
        targetRevision: applicationset
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
---
