apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: argo-workflows
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: "*"
    helm:
      values: |
        controller:
          containerRuntimeExecutor: k8sapi  
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true


